---
title: "R Project 1 - Hello R"
author: "Dat Duong"
date: "1/23/2020"
output: 
  html_document: 
    fig_height: 6
    fig_width: 8
    highlight: monochrome
    theme: cosmo
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

A data frame with 1846 rows and 3 variables.
The variables in clude dataset, x-values, and y values.

### Exercise 2
```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3
```{r plot-dino2, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r cor-dino2}
dino_data %>%
  summarize(r = cor(x, y))
```
### Exercise 4
```{r plot-dino3, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r cor-dino3}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
  theme(legend.position = "none")
```
```{r}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```


